### PR TITLE
Faster divide and conquer algorithm.

### PR DESCRIPTION
**Pull request by JulienPalard**
I did not took the time to compute the big-O complexity, but it's obvious it's better and not premature.

Also I need one function less.

### CODE REVIEW

**Comment by Seluj78** [comment]
Hi, thanks for you PR.

The thing is, with your changes, it will consequently slow down the sort algorithm.

You are calling recursively the miracle sort, which reduces the chances of a miracle happening

**Comment by Abdur-rahmaanJ** [comment]
Knowing that with simplish looking codes, someone would've PR something to complexify it.

**Comment by JulienPalard** [comment]
> which reduces the chances of a miracle happening

You'd be right, BUT, your version is expecting one really really big miracle to happen while mine uses many small easy miracles.

I expect small easy miracles to happen way more often than really big miracles (it lacks scientifical study), if prooved right, my version could be faster, at least for small lists.

It's also well known that miracles often [happen in series](https://en.wikipedia.org/wiki/Our_Lady_of_F%C3%A1tima#Marian_apparitions), my implementation make good use of this feature.

@Abdur-rahmaanJ:
> someone would've PR something to complexify it

Not sure if you've read my PR or just trolling here, but I'm simplifying the code (see `git diff --stat`, removed a function, ...).

**Comment by Seluj78** [comment]
> I expect small easy miracles to happen way more often than really big miracles (it lacks scientifical study), if prooved right, my version could be faster, at least for small lists.

I'd need to see that

> It's also well known that miracles often [happen in series](https://en.wikipedia.org/wiki/Our_Lady_of_F%C3%A1tima#Marian_apparitions), my implementation make good use of this feature.

The thing is, one miracle is rare enough, so once it happens it's sorted and done, while your implementation will wait for another one and another one...

**Comment by Abdur-rahmaanJ** [comment]
@JulienPalard I no longer remember but sure the original code reads better. I was probably joking here.

**Pull request closed without merging**
